# PHP as Linux Web App on Azure
# Build, package and deploy your PHP project to Azure Web App.
# Add steps that run tests and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
  - main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'Visual Studio Ultimate con MSDN (59dc1cc3-4719-4700-9b47-0a4c350bc072)'

  # Web app name
  webAppName: 'my-appointments'

  # Environment name
  environmentName: 'my-appointments'

  # Root folder under which your composer.json file is available.
  rootFolder: $(System.DefaultWorkingDirectory)
  
stages:
  - stage: Build
    displayName: Build stage
    variables:
      phpVersion: "7.3"
    jobs:
      - job: BuildJob
        steps:
          - script: |
              sudo update-alternatives --set php /usr/bin/php$(phpVersion)
              sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
              sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
              sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
              sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
              php -version
            workingDirectory: $(rootFolder)
            displayName: "Use PHP version $(phpVersion)"            
          
          - script: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
            workingDirectory: $(rootFolder)
            displayName: 'Composer install'
          
          - script: |
              cp .env.example .env
              php artisan key:generate --force
            displayName: "Running Laravel config & optimizations"
          
                    
#Run on WebSSH from Azure App Service: 
# php artisan migrate:refresh --seed --env=production --force --no-interaction
# php artisan passport:install

          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: '$(rootFolder)'
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              replaceExistingArchive: true
      
          - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            displayName: 'Upload package'
            artifact: drop        
  - stage: Deploy
    displayName: 'Deploy Web App'
    dependsOn: Build
    condition: succeeded()
    jobs:
    - deployment: DeploymentJob
      environment: $(environmentName)
      strategy:
        runOnce:
          deploy:
            steps:             
            - task: PublishBuildArtifacts@1
              inputs:
                PathtoPublish: '$(Build.ArtifactStagingDirectory)'
                ArtifactName: 'drop'
                publishLocation: 'Container'